/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ClassCategory = { 'jee' : null } |
  { 'neet' : null } |
  { 'class10' : null } |
  { 'class11' : null } |
  { 'class12' : null };
export type ExternalBlob = Uint8Array;
export interface Material {
  'id' : string,
  'title' : string,
  'subject' : Subject,
  'classCategory' : ClassCategory,
  'blob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'isActive' : boolean,
  'downloadCount' : bigint,
  'materialType' : MaterialType,
  'uploadedAt' : Time,
  'uploadedBy' : Principal,
}
export interface MaterialInput {
  'title' : string,
  'subject' : Subject,
  'classCategory' : ClassCategory,
  'blob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'materialType' : MaterialType,
}
export type MaterialType = { 'other' : null } |
  { 'ebook' : null } |
  { 'videoNotes' : null } |
  { 'testSeries' : null } |
  { 'notes' : null } |
  { 'samplePaper' : null } |
  { 'solutions' : null };
export type Subject = { 'maths' : null } |
  { 'biology' : null } |
  { 'hindi' : null } |
  { 'other' : null } |
  { 'socialScience' : null } |
  { 'chemistry' : null } |
  { 'physics' : null } |
  { 'english' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMaterial' : ActorMethod<[MaterialInput], string>,
  'deleteMaterial' : ActorMethod<[string], undefined>,
  'filterByClass' : ActorMethod<[ClassCategory], Array<Material>>,
  'filterBySubject' : ActorMethod<[Subject], Array<Material>>,
  'filterByType' : ActorMethod<[MaterialType], Array<Material>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaterial' : ActorMethod<[string], Material>,
  'getMaterialCount' : ActorMethod<[], bigint>,
  'getMaterialsByClass' : ActorMethod<
    [],
    Array<[ClassCategory, Array<Material>]>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementDownloadCount' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMaterials' : ActorMethod<[], Array<Material>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchByTitle' : ActorMethod<[string], Array<Material>>,
  'updateMaterial' : ActorMethod<[string, MaterialInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];