/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Subject = IDL.Variant({
  'maths' : IDL.Null,
  'biology' : IDL.Null,
  'hindi' : IDL.Null,
  'other' : IDL.Null,
  'socialScience' : IDL.Null,
  'chemistry' : IDL.Null,
  'physics' : IDL.Null,
  'english' : IDL.Null,
});
export const ClassCategory = IDL.Variant({
  'jee' : IDL.Null,
  'neet' : IDL.Null,
  'class10' : IDL.Null,
  'class11' : IDL.Null,
  'class12' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MaterialType = IDL.Variant({
  'other' : IDL.Null,
  'ebook' : IDL.Null,
  'videoNotes' : IDL.Null,
  'testSeries' : IDL.Null,
  'notes' : IDL.Null,
  'samplePaper' : IDL.Null,
  'solutions' : IDL.Null,
});
export const MaterialInput = IDL.Record({
  'title' : IDL.Text,
  'subject' : Subject,
  'classCategory' : ClassCategory,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'materialType' : MaterialType,
});
export const Time = IDL.Int;
export const Material = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : Subject,
  'classCategory' : ClassCategory,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'isActive' : IDL.Bool,
  'downloadCount' : IDL.Nat,
  'materialType' : MaterialType,
  'uploadedAt' : Time,
  'uploadedBy' : IDL.Principal,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMaterial' : IDL.Func([MaterialInput], [IDL.Text], []),
  'deleteMaterial' : IDL.Func([IDL.Text], [], []),
  'filterByClass' : IDL.Func([ClassCategory], [IDL.Vec(Material)], ['query']),
  'filterBySubject' : IDL.Func([Subject], [IDL.Vec(Material)], ['query']),
  'filterByType' : IDL.Func([MaterialType], [IDL.Vec(Material)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMaterial' : IDL.Func([IDL.Text], [Material], ['query']),
  'getMaterialCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMaterialsByClass' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ClassCategory, IDL.Vec(Material)))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementDownloadCount' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Material)], ['query']),
  'updateMaterial' : IDL.Func([IDL.Text, MaterialInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Subject = IDL.Variant({
    'maths' : IDL.Null,
    'biology' : IDL.Null,
    'hindi' : IDL.Null,
    'other' : IDL.Null,
    'socialScience' : IDL.Null,
    'chemistry' : IDL.Null,
    'physics' : IDL.Null,
    'english' : IDL.Null,
  });
  const ClassCategory = IDL.Variant({
    'jee' : IDL.Null,
    'neet' : IDL.Null,
    'class10' : IDL.Null,
    'class11' : IDL.Null,
    'class12' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MaterialType = IDL.Variant({
    'other' : IDL.Null,
    'ebook' : IDL.Null,
    'videoNotes' : IDL.Null,
    'testSeries' : IDL.Null,
    'notes' : IDL.Null,
    'samplePaper' : IDL.Null,
    'solutions' : IDL.Null,
  });
  const MaterialInput = IDL.Record({
    'title' : IDL.Text,
    'subject' : Subject,
    'classCategory' : ClassCategory,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'materialType' : MaterialType,
  });
  const Time = IDL.Int;
  const Material = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : Subject,
    'classCategory' : ClassCategory,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'isActive' : IDL.Bool,
    'downloadCount' : IDL.Nat,
    'materialType' : MaterialType,
    'uploadedAt' : Time,
    'uploadedBy' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMaterial' : IDL.Func([MaterialInput], [IDL.Text], []),
    'deleteMaterial' : IDL.Func([IDL.Text], [], []),
    'filterByClass' : IDL.Func([ClassCategory], [IDL.Vec(Material)], ['query']),
    'filterBySubject' : IDL.Func([Subject], [IDL.Vec(Material)], ['query']),
    'filterByType' : IDL.Func([MaterialType], [IDL.Vec(Material)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMaterial' : IDL.Func([IDL.Text], [Material], ['query']),
    'getMaterialCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMaterialsByClass' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ClassCategory, IDL.Vec(Material)))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementDownloadCount' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMaterials' : IDL.Func([], [IDL.Vec(Material)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Material)], ['query']),
    'updateMaterial' : IDL.Func([IDL.Text, MaterialInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };