/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MaterialInput {
    title: string;
    subject: Subject;
    classCategory: ClassCategory;
    blob: ExternalBlob;
    description: string;
    fileName: string;
    fileSize: bigint;
    materialType: MaterialType;
}
export interface Material {
    id: string;
    title: string;
    subject: Subject;
    classCategory: ClassCategory;
    blob: ExternalBlob;
    description: string;
    fileName: string;
    fileSize: bigint;
    isActive: boolean;
    downloadCount: bigint;
    materialType: MaterialType;
    uploadedAt: Time;
    uploadedBy: Principal;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ClassCategory {
    jee = "jee",
    neet = "neet",
    class10 = "class10",
    class11 = "class11",
    class12 = "class12"
}
export enum MaterialType {
    other = "other",
    ebook = "ebook",
    videoNotes = "videoNotes",
    testSeries = "testSeries",
    notes = "notes",
    samplePaper = "samplePaper",
    solutions = "solutions"
}
export enum Subject {
    maths = "maths",
    biology = "biology",
    hindi = "hindi",
    other = "other",
    socialScience = "socialScience",
    chemistry = "chemistry",
    physics = "physics",
    english = "english"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMaterial(input: MaterialInput): Promise<string>;
    deleteMaterial(id: string): Promise<void>;
    filterByClass(classCategory: ClassCategory): Promise<Array<Material>>;
    filterBySubject(subject: Subject): Promise<Array<Material>>;
    filterByType(materialType: MaterialType): Promise<Array<Material>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMaterial(id: string): Promise<Material>;
    getMaterialCount(): Promise<bigint>;
    getMaterialsByClass(): Promise<Array<[ClassCategory, Array<Material>]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementDownloadCount(id: string): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listMaterials(): Promise<Array<Material>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchByTitle(searchTerm: string): Promise<Array<Material>>;
    updateMaterial(id: string, input: MaterialInput): Promise<void>;
}
import type { ClassCategory as _ClassCategory, ExternalBlob as _ExternalBlob, Material as _Material, MaterialInput as _MaterialInput, MaterialType as _MaterialType, Subject as _Subject, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMaterial(arg0: MaterialInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaterial(await to_candid_MaterialInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaterial(await to_candid_MaterialInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteMaterial(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaterial(arg0);
            return result;
        }
    }
    async filterByClass(arg0: ClassCategory): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByClass(to_candid_ClassCategory_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByClass(to_candid_ClassCategory_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterBySubject(arg0: Subject): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterBySubject(to_candid_Subject_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterBySubject(to_candid_Subject_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByType(arg0: MaterialType): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByType(to_candid_MaterialType_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByType(to_candid_MaterialType_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterial(arg0: string): Promise<Material> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterial(arg0);
                return from_candid_Material_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterial(arg0);
            return from_candid_Material_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaterialCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialCount();
            return result;
        }
    }
    async getMaterialsByClass(): Promise<Array<[ClassCategory, Array<Material>]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaterialsByClass();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaterialsByClass();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementDownloadCount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementDownloadCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementDownloadCount(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMaterials(): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMaterials();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMaterials();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchByTitle(arg0: string): Promise<Array<Material>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByTitle(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByTitle(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateMaterial(arg0: string, arg1: MaterialInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaterial(arg0, await to_candid_MaterialInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaterial(arg0, await to_candid_MaterialInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ClassCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassCategory): ClassCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MaterialType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MaterialType): MaterialType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_Material_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Material): Promise<Material> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Subject_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subject): Subject {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    subject: _Subject;
    classCategory: _ClassCategory;
    blob: _ExternalBlob;
    description: string;
    fileName: string;
    fileSize: bigint;
    isActive: boolean;
    downloadCount: bigint;
    materialType: _MaterialType;
    uploadedAt: _Time;
    uploadedBy: Principal;
}): Promise<{
    id: string;
    title: string;
    subject: Subject;
    classCategory: ClassCategory;
    blob: ExternalBlob;
    description: string;
    fileName: string;
    fileSize: bigint;
    isActive: boolean;
    downloadCount: bigint;
    materialType: MaterialType;
    uploadedAt: Time;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        title: value.title,
        subject: from_candid_Subject_n22(_uploadFile, _downloadFile, value.subject),
        classCategory: from_candid_ClassCategory_n24(_uploadFile, _downloadFile, value.classCategory),
        blob: await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        fileName: value.fileName,
        fileSize: value.fileSize,
        isActive: value.isActive,
        downloadCount: value.downloadCount,
        materialType: from_candid_MaterialType_n27(_uploadFile, _downloadFile, value.materialType),
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_ClassCategory, Array<_Material>]): Promise<[ClassCategory, Array<Material>]> {
    return [
        from_candid_ClassCategory_n24(_uploadFile, _downloadFile, value[0]),
        await from_candid_vec_n19(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    maths: null;
} | {
    biology: null;
} | {
    hindi: null;
} | {
    other: null;
} | {
    socialScience: null;
} | {
    chemistry: null;
} | {
    physics: null;
} | {
    english: null;
}): Subject {
    return "maths" in value ? Subject.maths : "biology" in value ? Subject.biology : "hindi" in value ? Subject.hindi : "other" in value ? Subject.other : "socialScience" in value ? Subject.socialScience : "chemistry" in value ? Subject.chemistry : "physics" in value ? Subject.physics : "english" in value ? Subject.english : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jee: null;
} | {
    neet: null;
} | {
    class10: null;
} | {
    class11: null;
} | {
    class12: null;
}): ClassCategory {
    return "jee" in value ? ClassCategory.jee : "neet" in value ? ClassCategory.neet : "class10" in value ? ClassCategory.class10 : "class11" in value ? ClassCategory.class11 : "class12" in value ? ClassCategory.class12 : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    ebook: null;
} | {
    videoNotes: null;
} | {
    testSeries: null;
} | {
    notes: null;
} | {
    samplePaper: null;
} | {
    solutions: null;
}): MaterialType {
    return "other" in value ? MaterialType.other : "ebook" in value ? MaterialType.ebook : "videoNotes" in value ? MaterialType.videoNotes : "testSeries" in value ? MaterialType.testSeries : "notes" in value ? MaterialType.notes : "samplePaper" in value ? MaterialType.samplePaper : "solutions" in value ? MaterialType.solutions : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Material>): Promise<Array<Material>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Material_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_ClassCategory, Array<_Material>]>): Promise<Array<[ClassCategory, Array<Material>]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n33(_uploadFile, _downloadFile, x)));
}
function to_candid_ClassCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassCategory): _ClassCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_MaterialInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialInput): Promise<_MaterialInput> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_MaterialType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialType): _MaterialType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Subject_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): _Subject {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    subject: Subject;
    classCategory: ClassCategory;
    blob: ExternalBlob;
    description: string;
    fileName: string;
    fileSize: bigint;
    materialType: MaterialType;
}): Promise<{
    title: string;
    subject: _Subject;
    classCategory: _ClassCategory;
    blob: _ExternalBlob;
    description: string;
    fileName: string;
    fileSize: bigint;
    materialType: _MaterialType;
}> {
    return {
        title: value.title,
        subject: to_candid_Subject_n12(_uploadFile, _downloadFile, value.subject),
        classCategory: to_candid_ClassCategory_n14(_uploadFile, _downloadFile, value.classCategory),
        blob: await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        fileName: value.fileName,
        fileSize: value.fileSize,
        materialType: to_candid_MaterialType_n17(_uploadFile, _downloadFile, value.materialType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subject): {
    maths: null;
} | {
    biology: null;
} | {
    hindi: null;
} | {
    other: null;
} | {
    socialScience: null;
} | {
    chemistry: null;
} | {
    physics: null;
} | {
    english: null;
} {
    return value == Subject.maths ? {
        maths: null
    } : value == Subject.biology ? {
        biology: null
    } : value == Subject.hindi ? {
        hindi: null
    } : value == Subject.other ? {
        other: null
    } : value == Subject.socialScience ? {
        socialScience: null
    } : value == Subject.chemistry ? {
        chemistry: null
    } : value == Subject.physics ? {
        physics: null
    } : value == Subject.english ? {
        english: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ClassCategory): {
    jee: null;
} | {
    neet: null;
} | {
    class10: null;
} | {
    class11: null;
} | {
    class12: null;
} {
    return value == ClassCategory.jee ? {
        jee: null
    } : value == ClassCategory.neet ? {
        neet: null
    } : value == ClassCategory.class10 ? {
        class10: null
    } : value == ClassCategory.class11 ? {
        class11: null
    } : value == ClassCategory.class12 ? {
        class12: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MaterialType): {
    other: null;
} | {
    ebook: null;
} | {
    videoNotes: null;
} | {
    testSeries: null;
} | {
    notes: null;
} | {
    samplePaper: null;
} | {
    solutions: null;
} {
    return value == MaterialType.other ? {
        other: null
    } : value == MaterialType.ebook ? {
        ebook: null
    } : value == MaterialType.videoNotes ? {
        videoNotes: null
    } : value == MaterialType.testSeries ? {
        testSeries: null
    } : value == MaterialType.notes ? {
        notes: null
    } : value == MaterialType.samplePaper ? {
        samplePaper: null
    } : value == MaterialType.solutions ? {
        solutions: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
